Class {
	#name : #GAODBCConnection,
	#superclass : #GAODBCObject,
	#category : #'Garage-ODBC'
}

{ #category : #'as yet unclassified' }
GAODBCConnection class >> connect: aString [

	
]

{ #category : #'instance creation' }
GAODBCConnection class >> sqlConnect: handle 
	server: server
	serverLength: serverLength 
	username: username
	usernameLength: usernameLength 
	authentication: auth 
	authenticationSize: authLength [
	
	
]
